import { MediaItem } from '../types/api';

export const mockMediaItems: MediaItem[] = [
  {
    hash: "abc123",
    media_type: "movie",
    media_title: "The Matrix",
    season: null,
    episode: null,
    release_year: 1999,
    pipeline_status: "processed",
    error_status: false,
    error_condition: null,
    rejection_status: "unfiltered",
    rejection_reason: null,
    parent_path: null,
    target_path: null,
    original_title: "The Matrix (1999) [1080p] [BluRay]",
    original_path: null,
    original_link: "https://example.com/matrix",
    rss_source: null,
    uploader: null,
    genre: ["Action", "Sci-Fi"],
    language: ["en"],
    rt_score: 87,
    metascore: 73,
    imdb_rating: 8.7,
    imdb_votes: 1800000,
    imdb_id: "tt0133093",
    resolution: "1080p",
    video_codec: "x264",
    upload_type: "BluRay",
    audio_codec: "DTS",
    created_at: "2024-03-15T10:00:00Z",
    updated_at: "2024-03-15T10:00:00Z",
    tmdb_id: 603
  },
  {
    hash: "def456",
    media_type: "tv",
    media_title: "Breaking Bad",
    season: 1,
    episode: 1,
    release_year: 2008,
    pipeline_status: "processed",
    error_status: false,
    error_condition: null,
    rejection_status: "accepted",
    rejection_reason: null,
    parent_path: null,
    target_path: null,
    original_title: "Breaking Bad S01E01 [1080p] [WEB-DL]",
    original_path: null,
    original_link: "https://example.com/breakingbad",
    rss_source: null,
    uploader: null,
    genre: ["Crime", "Drama", "Thriller"],
    language: ["en"],
    rt_score: 96,
    metascore: 85,
    imdb_rating: 9.5,
    imdb_votes: 2000000,
    imdb_id: "tt0903747",
    resolution: "1080p",
    video_codec: "x264",
    upload_type: "WEB-DL",
    audio_codec: "AAC",
    created_at: "2024-03-15T11:00:00Z",
    updated_at: "2024-03-15T11:00:00Z",
    tmdb_id: 1396
  },
  {
    hash: "ghi789",
    media_type: "movie",
    media_title: "Inception",
    season: null,
    episode: null,
    release_year: 2010,
    pipeline_status: "error",
    error_status: true,
    error_condition: "Failed to process metadata",
    rejection_status: "rejected",
    rejection_reason: "Invalid video format",
    parent_path: null,
    target_path: null,
    original_title: "Inception (2010) [720p] [WEBRip]",
    original_path: null,
    original_link: "https://example.com/inception",
    rss_source: null,
    uploader: null,
    genre: ["Action", "Sci-Fi", "Thriller"],
    language: ["en"],
    rt_score: 87,
    metascore: 74,
    imdb_rating: 8.8,
    imdb_votes: 2200000,
    imdb_id: "tt1375666",
    resolution: "720p",
    video_codec: "x264",
    upload_type: "WEBRip",
    audio_codec: "AAC",
    created_at: "2024-03-15T12:00:00Z",
    updated_at: "2024-03-15T12:00:00Z",
    tmdb_id: 27205
  }
]; 